function Hd = ecgbandp
%ECGBANDP 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 02-Mar-2022 22:25:09

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 500;  % Sampling Frequency

Fstop1 = 0.01;         % First Stopband Frequency
Fpass1 = 0.05;           % First Passband Frequency
Fpass2 = 50;          % Second Passband Frequency
Fstop2 = 60;          % Second Stopband Frequency
Astop1 = 0.1;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 60;          % Second Stopband Attenuation (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
